// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt6LnaoeOGAn-ybZRzyUfaXDbf9UtDL7U',
    appId: '1:420256992236:web:4d0187ead9383cf0bbcec9',
    messagingSenderId: '420256992236',
    projectId: 'netflix-168b7',
    authDomain: 'netflix-168b7.firebaseapp.com',
    storageBucket: 'netflix-168b7.appspot.com',
    measurementId: 'G-ZZ1F9LZK89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWxSfOCmemCn8Pxfqa_lRD5qvdZLbNtCI',
    appId: '1:420256992236:android:e7264322b333985fbbcec9',
    messagingSenderId: '420256992236',
    projectId: 'netflix-168b7',
    storageBucket: 'netflix-168b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAUsGxA373nDi9CadDEebM6mMeAZ1K5dk',
    appId: '1:420256992236:ios:9190db92e79b251cbbcec9',
    messagingSenderId: '420256992236',
    projectId: 'netflix-168b7',
    storageBucket: 'netflix-168b7.appspot.com',
    iosClientId: '420256992236-o0onhac2hlc1vo4gpoc3c8adud2s53j6.apps.googleusercontent.com',
    iosBundleId: 'com.example.netflixCloneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAUsGxA373nDi9CadDEebM6mMeAZ1K5dk',
    appId: '1:420256992236:ios:9190db92e79b251cbbcec9',
    messagingSenderId: '420256992236',
    projectId: 'netflix-168b7',
    storageBucket: 'netflix-168b7.appspot.com',
    iosClientId: '420256992236-o0onhac2hlc1vo4gpoc3c8adud2s53j6.apps.googleusercontent.com',
    iosBundleId: 'com.example.netflixCloneApp',
  );
}
