// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7uBio0xdrXBq7i7o0wdWI5gWTn8jfT1M',
    appId: '1:308704033836:web:05a52f96017765c872e589',
    messagingSenderId: '308704033836',
    projectId: 'httptest-f4e1d',
    authDomain: 'httptest-f4e1d.firebaseapp.com',
    storageBucket: 'httptest-f4e1d.appspot.com',
    measurementId: 'G-0VFN90BRGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1m0xu8525zgHr4RYfTnMIRPTqWDh2caw',
    appId: '1:308704033836:android:e93820efe70d1f9c72e589',
    messagingSenderId: '308704033836',
    projectId: 'httptest-f4e1d',
    storageBucket: 'httptest-f4e1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8dF673RRx_RaPbe8Bp-YhlSVxvc43hFs',
    appId: '1:308704033836:ios:dc383fe6b18b128172e589',
    messagingSenderId: '308704033836',
    projectId: 'httptest-f4e1d',
    storageBucket: 'httptest-f4e1d.appspot.com',
    iosClientId:
        '308704033836-jol1j60va6qdfu9h72dnah1gb6cpasos.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8dF673RRx_RaPbe8Bp-YhlSVxvc43hFs',
    appId: '1:308704033836:ios:dc383fe6b18b128172e589',
    messagingSenderId: '308704033836',
    projectId: 'httptest-f4e1d',
    storageBucket: 'httptest-f4e1d.appspot.com',
    iosClientId:
        '308704033836-jol1j60va6qdfu9h72dnah1gb6cpasos.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseListApp',
  );
}
